protocol = "horiba-micro-hr"
doc = "Horiba Jobin-Yvon Micro-Hr monochromator."
traits = ["has-turret", "is-homeable", "has-limits", "is-daemon"]
hardware = ["horiba:microhr"]

[links]
source = "https://gitlab.com/yaq/yaqd-horiba"
bugtracker = "https://gitlab.com/yaq/yaqd-horiba/issues"
manufacturer = "https://www.horiba.com/en_en/products/detail/action/show/Product/microhr-series-1591/"

[installation]
PyPI = "https://pypi.org/project/yaqd-horiba/"
conda-forge = "https://anaconda.org/conda-forge/yaqd-horiba/"

[[types]]
type = "record"
name = "horiba_grating"
fields = [
    {"name"="index", "type"="int", "default"=0},
    {"name"="lines_per_mm", "type"="float", "default"=1200.0},
]

[config]
gratings.type = {"type"="map", "values"="horiba_grating"}
gratings.default = {"default"={}}
gratings.doc = "Map which gives a label to a grating with its lines/mm and index"

make.default = "Horiba Jobin-Yvon"
model.default = "MicroHR"

